//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMed.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cijepljenje
    {
        public int cijepljenjeID { get; set; }
        public string slucaj { get; set; }
        public Nullable<System.DateTime> datume { get; set; }
        public string vrsta_cijepljenja { get; set; }
        public string prirava_cjepiva { get; set; }
        public string broj_doze { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> djelatniciID { get; set; }
        public Nullable<int> pacijentiID { get; set; }
    
        public virtual pacijenti pacijenti { get; set; }
        public virtual djelatnici djelatnici { get; set; }
    }
}
