//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMed.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseMedDBEntities : DbContext
    {
        public HouseMedDBEntities()
            : base("name=HouseMedDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cijepljenje> cijepljenje { get; set; }
        public virtual DbSet<evidencija_hospitalizacije> evidencija_hospitalizacije { get; set; }
        public virtual DbSet<lijekovi> lijekovi { get; set; }
        public virtual DbSet<pacijenti> pacijenti { get; set; }
        public virtual DbSet<raspored> raspored { get; set; }
        public virtual DbSet<sifra_zdrv_ustanove> sifra_zdrv_ustanove { get; set; }
        public virtual DbSet<uputnica> uputnica { get; set; }
        public virtual DbSet<recepti> recepti { get; set; }
        public virtual DbSet<djelatnici> djelatnici { get; set; }
        public virtual DbSet<postupci> postupci { get; set; }
        public virtual DbSet<potvrde> potvrde { get; set; }
    }
}
