//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMed.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacijenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacijenti()
        {
            this.cijepljenje = new HashSet<cijepljenje>();
            this.evidencija_hospitalizacije = new HashSet<evidencija_hospitalizacije>();
            this.raspored = new HashSet<raspored>();
            this.uputnica = new HashSet<uputnica>();
            this.recepti = new HashSet<recepti>();
            this.postupci = new HashSet<postupci>();
            this.potvrde = new HashSet<potvrde>();
        }
    
        public int pacijentiID { get; set; }
        public Nullable<int> MBO { get; set; }
        public Nullable<int> OIB { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string spol { get; set; }
        public string mjesto { get; set; }
        public string adresa { get; set; }
        public string drzava { get; set; }
        public string telefon { get; set; }
        public string mobitel { get; set; }
        public string email { get; set; }
        public Nullable<int> sifra_zdrv_ustanoveID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cijepljenje> cijepljenje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencija_hospitalizacije> evidencija_hospitalizacije { get; set; }
        public virtual sifra_zdrv_ustanove sifra_zdrv_ustanove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raspored> raspored { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uputnica> uputnica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepti> recepti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postupci> postupci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<potvrde> potvrde { get; set; }
    }
}
