//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMed.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class potvrde
    {
        public int potvrdeID { get; set; }
        public string svrha { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> djelatniciID { get; set; }
        public Nullable<int> pacijentiID { get; set; }
    
        public virtual djelatnici djelatnici { get; set; }
        public virtual pacijenti pacijenti { get; set; }
    }
}
